run-name: build aseprite
on: push
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: get deps
        run: | 
          choco install wget -y --no-progress
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia
      - uses: hendrikmuhs/ccache-action@v1
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generating Makefiles
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_SCRIPTING=on \
          -DENABLE_CCACHE=off \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=skia \
          -DSKIA_LIBRARY_DIR=skia/out/Release-x64
      - name: Compiling
        shell: bash
        run: |
          cd build && ninja
      - uses: actions/upload-artifact@v4
        with:
          name: executable
          path: ./build/bin/asprite.*
